# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.15.0

inherit perl-module

S=${WORKDIR}/CPAN-1.9402-i3hfW2

DESCRIPTION="Perl Archive browse and download"
HOMEPAGE="http://search.cpan.org/search?query=CPAN&mode=dist"
SRC_URI="mirror://cpan/authors/id/A/AN/ANDK/CPAN-1.9402.tar.gz"


IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="x86"

DEPEND="dev-lang/perl"
