# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.15.0

inherit perl-module

S=${WORKDIR}/Test-Reporter-1.54

DESCRIPTION="sends test results to cpan-testers@perl.org"
HOMEPAGE="http://search.cpan.org/search?query=Test-Reporter&mode=dist"
SRC_URI="mirror://cpan/authors/id/D/DA/DAGOLDEN/Test-Reporter-1.54.tar.gz"


IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="x86"

DEPEND="dev-lang/perl"
