# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.15.0

inherit perl-module

S=${WORKDIR}/Geo-IPfree-0.4

DESCRIPTION="No description available"
HOMEPAGE="http://search.cpan.org/search?query=Geo-IPfree&mode=dist"
SRC_URI="mirror://cpan/authors/id/B/BR/BRICAS/Geo-IPfree-0.4.tar.gz"


IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="x86"

DEPEND="dev-lang/perl"
