# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.15.0

inherit perl-module

S=${WORKDIR}/IO-CaptureOutput-1.1101

DESCRIPTION="No description available"
HOMEPAGE="http://search.cpan.org/search?query=IO-CaptureOutput&mode=dist"
SRC_URI="mirror://cpan/authors/id/D/DA/DAGOLDEN/IO-CaptureOutput-1.1101.tar.gz"


IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="x86"

DEPEND="dev-lang/perl"
